### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by RedNekoderr** [Makrennel/hyprland-void#10]
About 5 days ago, after hyprland update, I and another person had the same error in the final stages of the build:
`
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/Compositor.cpp.o: in function `CCompositor::initServer()':
Compositor.cpp:(.text+0x116ca): undefined reference to `wlr_drm_lease_v1_manager_create'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/events/Misc.cpp.o: in function `Events::listener_leaseRequest(wl_listener*, void*)':
Misc.cpp:(.text+0x578): undefined reference to `wlr_drm_lease_request_v1_grant'
/usr/bin/ld: Misc.cpp:(.text+0x59e): undefined reference to `wlr_drm_lease_request_v1_reject'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/helpers/Monitor.cpp.o: in function `CMonitor::onConnect(bool)':
Monitor.cpp:(.text+0x2485): undefined reference to `wlr_backend_is_drm'
/usr/bin/ld: Monitor.cpp:(.text+0x2dcc): undefined reference to `wlr_drm_lease_v1_manager_offer_output'
/usr/bin/ld: CMakeFiles/Hyprland.dir/src/render/Renderer.cpp.o: in function `CHyprRenderer::applyMonitorRule(CMonitor*, SMonitorRule*, bool)':
Renderer.cpp:(.text+0xc369): undefined reference to `wlr_output_is_drm'
/usr/bin/ld: Renderer.cpp:(.text+0xc82c): undefined reference to `wlr_drm_connector_add_mode'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
=> ERROR: hyprland-0.29.1_1: do_build: 'cmake --build ./build --config Release --target all -j${XBPS_MAKEJOBS}' exited with 1
=> ERROR:   in do_build() at srcpkgs/hyprland/template:78
`

**Comment by Makrennel** [comment]
> About 5 days ago, after hyprland update, I and another person had the same error in the final stages of the build: 

Interesting, I've just tried rerunning the build script from another fresh void-packages clone and it fails for the same reason. The last clone I did when testing 0.29.1 still works. I'm not sure what's changed yet or if I can fix it, but I'll look into it.

**Comment by 22h49** [comment]
For anyone stumbling upon this, the problem is that `wlroots` does not have some required dependencies and therefore compiles without a couple of functions and thus the linker complains.

the solution is to add

`libdisplay-info-devel`
into the `makedepends` and
`libdisplay-info` into the `depends`

@Makrennel I can open a pull request if you want me to.

I also managed to get it to build under musl so I can open a PR for that as well.

**Comment by Makrennel** [comment]
> @Makrennel I can open a pull request if you want me to.
> 
> I also managed to get it to build under musl so I can open a PR for that as well.

That would be a great help, please do open PRs.

**Comment by Makrennel** [comment]
@22h49 I am trying to update to v0.30.0 so I went ahead and fixed the libdisplay-info issue (it was added to upstream void-packages). I'd be happy to accept a musl PR.

**Comment by Makrennel** [comment]
> I am trying to update to v0.30.0

... Actually, this may not be updating to 0.30.0 any time soon. It requires C++ 20 features and void's still uses gcc 12.2.0, and knowing void, who knows how long it'll take to get [gcc 13](https://github.com/void-linux/void-packages/pull/45500) - it took the entirety of 2022 to go from 10 to 12....

**Comment by 22h49** [comment]
>  I'd be happy to accept a musl PR.


Yeah sorry for the delay I had a busy week, will try to do it today.

**Comment by ccptr** [comment]
> It requires C++ 20 features and void's still uses gcc 12.2.0, and knowing void, who knows how long it'll take to get [gcc 13](https://github.com/void-linux/void-packages/pull/45500)

Would it be possible to use clang for the time being? I wasn't thinking and uninstalled Hyprland when I was initially trying to get it to build, and now I don't think I'll be able to get it back :cry:

I tried a little bit today, but I haven't been able to get CMake to do the right thing/pass the right flags (I'm stuck with `error: invalid value 'gnu++23' in '-std=gnu++23'` now, it needs to be `gnu++2b`)

**Comment by Makrennel** [comment]
> Would it be possible to use clang for the time being? I wasn't thinking and uninstalled Hyprland when I was initially trying to get it to build, and now I don't think I'll be able to get it back :cry:
> 
> I tried a little bit today, but I haven't been able to get CMake to do the right thing/pass the right flags (I'm stuck with `error: invalid value 'gnu++23' in '-std=gnu++23'` now, it needs to be `gnu++2b`)

@ccptr I've attempted to use clang by modifying the `common/xbps-src/shutils/common.sh` file, but it was unsuccessful. I'm not sure if clang 15 supports c++ 20, but if it does you would probably have to somehow add an argument like `-std=c++20`. I haven't had the chance to figure this out though.

If you just want to reinstall Hyprland, can you not install the older version stored in `hostdir/binpkgs`? Or rebuild it with a fresh clone if you've removed that?

**Comment by ccptr** [comment]
I should probably mention that I was trying to build v0.31.0 :sweat_smile:

> I'm not sure if clang 15 supports c++ 20, but if it does you would probably have to somehow add an argument like -std=c++20.

According to the [Hyprland wiki](https://wiki.hyprland.org/Getting-Started/Installation/), it is now using C++ 23:
> Hyprland uses the C++23 standard, so both your compiler and your C++ library has to support that (`gcc>=13.0.0` or `clang>=15`). On Clang-based systems libc++ may be used by default, so until libc++ supports C++23 you have to pass `-stdlib=libstdc++` or switch to GCC.

So according to that it should be possible. When I was attempting to build it said to use c++2b for C++ 23.

> If you just want to reinstall Hyprland, can you not install the older version stored in hostdir/binpkgs? Or rebuild it with a fresh clone if you've removed that?

Thank you!!! I didn't realize that the built packages didn't get deleted. And no, I cannot build the old version:
<details><summary>`./xbps-src pkg hyprland` after following instructions in README</summary>

=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://repo-default.voidlinux.org/current/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
x86_64-repodata: 1854KB [avg rate: 312KB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/debug/x86_64-repodata' ...
x86_64-repodata: 871KB [avg rate: 375KB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
x86_64-repodata: 718KB [avg rate: 463KB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> hyprland-0.29.1_3: removing autodeps, please wait...
=> hyprland-0.29.1_3: building for x86_64...
   [host] jq-1.7_1: found (https://repo-default.voidlinux.org/current)
   [host] git-2.42.0_2: found (https://repo-default.voidlinux.org/current)
   [host] pkg-config-0.29.2_3: found (https://repo-default.voidlinux.org/current)
   [host] glslang-11.11.0_1: found (https://repo-default.voidlinux.org/current)
   [host] hwids-0.374_1: found (https://repo-default.voidlinux.org/current)
   [host] meson-1.2.0_2: found (https://repo-default.voidlinux.org/current)
   [host] cmake-3.27.6_1: found (https://repo-default.voidlinux.org/current)
   [host] ninja-1.11.1_4: found (https://repo-default.voidlinux.org/current)
   [host] autoconf-2.71_1: found (https://repo-default.voidlinux.org/current)
   [host] mk-configure-0.38.2_1: found (https://repo-default.voidlinux.org/current)
   [target] cairo-devel-1.18.0_1: found (https://repo-default.voidlinux.org/current)
   [target] libdisplay-info-devel-0.1.1_1: found (https://repo-default.voidlinux.org/current)
   [target] libliftoff-0.4.1_1: found (/host/binpkgs)
   [target] pango-devel-1.50.14_1: found (https://repo-default.voidlinux.org/current)
   [target] wlroots-devel-0.16.99_1: found (https://repo-default.voidlinux.org/current)
   [target] xorg-server-xwayland-23.2.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] cairo-1.18.0_1: found (https://repo-default.voidlinux.org/current)
   [runtime] glslang-11.11.0_1: found (https://repo-default.voidlinux.org/current)
   [runtime] libdisplay-info-0.1.1_1: found (/host/binpkgs)
   [runtime] libinput-1.23.0_1: found (https://repo-default.voidlinux.org/current)
   [runtime] libliftoff-0.4.1_1: found (/host/binpkgs)
   [runtime] libxcb-1.16_1: found (https://repo-default.voidlinux.org/current)
   [runtime] libXfixes-6.0.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] libxkbcommon-1.5.0_1: found (https://repo-default.voidlinux.org/current)
   [runtime] pango-1.50.14_1: found (https://repo-default.voidlinux.org/current)
   [runtime] pixman-0.42.2_1: found (https://repo-default.voidlinux.org/current)
   [runtime] polkit-121_1: found (https://repo-default.voidlinux.org/current)
   [runtime] Vulkan-ValidationLayers-1.3.231.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] vulkan-loader-1.3.231.2_1: found (https://repo-default.voidlinux.org/current)
   [runtime] wayland-1.22.0_1: found (https://repo-default.voidlinux.org/current)
   [runtime] wayland-protocols-1.32_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-proto-1.16.0_2: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-util-0.4.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-util-errors-1.0.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-util-keysyms-0.4.1_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-util-renderutil-0.3.10_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xcb-util-wm-0.4.2_1: found (https://repo-default.voidlinux.org/current)
   [runtime] xorg-server-xwayland-23.2.1_1: found (https://repo-default.voidlinux.org/current)
=> hyprland-0.29.1_3: installing host dependencies: jq-1.7_1 git-2.42.0_2 pkg-config-0.29.2_3 glslang-11.11.0_1 hwids-0.374_1 meson-1.2.0_2 cmake-3.27.6_1 ninja-1.11.1_4 autoconf-2.71_1 mk-configure-0.38.2_1 ...
=> hyprland-0.29.1_3: installing target dependencies: cairo-devel-1.18.0_1 libdisplay-info-devel-0.1.1_1 libliftoff-0.4.1_1 pango-devel-1.50.14_1 wlroots-devel-0.16.99_1 xorg-server-xwayland-23.2.1_1 ...
=> hyprland-0.29.1_3: removing autodeps, please wait...
=> ERROR: hyprland-0.29.1_3: failed to install target dependencies! (error 17)
3 packages will be downloaded:

125 packages will be installed:

  brotli-1.1.0_1 
  libpng-1.6.40_1 
  freetype-2.13.2_1 
  fontconfig-2.14.2_1 
  util-linux-common-2.38.1_4 
  libblkid-2.38.1_4 
  libmount-2.38.1_4 
  glib-2.78.0_3 
  libXau-1.0.11_1 
  libXdmcp-1.1.4_1 
  libxcb-1.16_1 
  libX11-1.8.7_1 
  libXext-1.3.5_1 
  libXrender-0.9.11_1 
  lzo-2.10_2 
  pixman-0.42.2_1 
  cairo-1.18.0_1 
  expat-devel-2.5.0_1 
  brotli-devel-1.1.0_1 
  bzip2-devel-1.0.8_2 
  zlib-devel-1.3_1 
  libpng-devel-1.6.40_1 
  freetype-devel-2.13.2_1 
  libuuid-2.38.1_4 
  libuuid-devel-2.38.1_4 
  fontconfig-devel-2.14.2_1 
  xorgproto-2023.2_1 
  libXau-devel-1.0.11_1 
  libXdmcp-devel-1.1.4_1 
  libxcb-devel-1.16_1 
  xtrans-1.5.0_1 
  libX11-devel-1.8.7_1 
  libXext-devel-1.3.5_1 
  libXrender-devel-0.9.11_1 
  dbus-libs-1.14.10_1 
  dbus-devel-1.14.10_1 
  liblzma-devel-5.4.4_1 
  libzstd-devel-1.5.5_2 
  elfutils-devel-0.189_1 
  libffi-devel-3.3_2 
  libblkid-devel-2.38.1_4 
  libmount-devel-2.38.1_4 
  pcre2-devel-10.42_1 
  libglib-devel-2.78.0_3 
  lzo-devel-2.10_2 
  pixman-devel-0.42.2_1 
  cairo-devel-1.18.0_1 
  libdisplay-info-0.1.1_1 
  libdisplay-info-devel-0.1.1_1 
  libpciaccess-0.16_1 
  libdrm-2.4.115_1 
  libliftoff-0.4.1_1 
  fribidi-1.0.13_1 
  fribidi-devel-1.0.13_1 
  graphite-1.3.14_1 
  graphite-devel-1.3.14_1 
  icu-libs-73.2_2 
  icu-devel-73.2_2 
  libharfbuzz-8.2.2_1 
  libxml2-2.11.4_4 
  harfbuzz-devel-8.2.2_1 
  libXft-2.3.8_1 
  libXft-devel-2.3.8_1 
  libdatrie-0.2.13_1 
  libthai-0.1.29_1 
  libdatrie-devel-0.2.13_1 
  libthai-devel-0.1.29_1 
  pango-1.50.14_1 
  pango-xft-1.50.14_1 
  pango-devel-1.50.14_1 
  Vulkan-Headers-1.3.231.1_1 
  eudev-libudev-3.2.12_1 
  eudev-libudev-devel-3.2.12_1 
  libpciaccess-devel-0.16_1 
  libdrm-devel-2.4.115_1 
  wayland-1.22.0_1 
  libgbm-23.1.3_1 
  libgbm-devel-23.1.3_1 
  libglvnd-1.6.0_1 
  libglvnd-devel-1.6.0_1 
  libevdev-1.13.0_1 
  libgudev-237_1 
  libwacom-2.8.0_1 
  mtdev-1.1.6_1 
  libinput-1.23.0_1 
  libinput-devel-1.23.0_1 
  libelogind-246.10_3 
  elogind-devel-246.10_3 
  libseat-0.8.0_1 
  libseat-devel-0.8.0_1 
  libxkbfile-1.1.2_1 
  xkbcomp-1.4.6_1 
  xkeyboard-config-2.40_1 
  libxkbcommon-1.5.0_1 
  libxkbcommon-x11-1.5.0_1 
  libxkbregistry-1.5.0_1 
  libxkbcommon-devel-1.5.0_1 
  vulkan-loader-1.3.231.2_1 
  wayland-devel-1.22.0_1 
  wayland-protocols-1.32_1 
  xcb-util-errors-1.0.1_1 
  xcb-util-renderutil-0.3.10_1 
  xcb-util-wm-0.4.2_1 
  wlroots0.16-0.16.2_1 
  xcb-proto-1.16.0_2 
  xcb-util-errors-devel-1.0.1_1 
  xcb-util-renderutil-devel-0.3.10_1 
  xcb-util-0.4.1_1 
  xcb-util-devel-0.4.1_1 
  xcb-util-wm-devel-0.4.2_1 
  wlroots0.16-devel-0.16.2_1 
  wlroots-devel-0.16.99_1 
  libfontenc-1.1.7_1 
  libXfont2-2.0.6_1 
  libepoxy-1.5.10_1 
  e2fsprogs-libs-1.47.0_1 
  libsasl-2.1.28_2 
  libldap-2.6.6_1 
  mit-krb5-libs-1.21.2_3 
  libtirpc-1.3.2_1 
  libxcvt-0.1.2_1 
  libxshmfence-1.3_2 
  nettle-3.9.1_1 
  xorg-server-common-21.1.9_1 
  xorg-server-xwayland-23.2.1_1 

Size to download:              448KB
Size required on disk:         185MB
Space available on disk:       239GB


[*] Downloading packages
wlroots0.16-0.16.2_1.x86_64.xbps.sig2: [512B 100%] 20MB/s ETA: 00m00s
wlroots0.16-0.16.2_1.x86_64.xbps.sig2: 512B [avg rate: 20MB/s]
wlroots0.16-0.16.2_1.x86_64.xbps: [383KB 1%] 163MB/s ETA: 00m00s
wlroots0.16-0.16.2_1.x86_64.xbps: [383KB 25%] 262KB/s ETA: 00m02s
wlroots0.16-0.16.2_1.x86_64.xbps: [383KB 45%] 132KB/s ETA: 00m02s
wlroots0.16-0.16.2_1.x86_64.xbps: 383KB [avg rate: 287KB/s]
wlroots0.16-0.16.2_1: verifying RSA signature...
wlroots0.16-devel-0.16.2_1.x86_64.xbps.sig2: [512B 100%] 20MB/s ETA: 00m00s
wlroots0.16-devel-0.16.2_1.x86_64.xbps.sig2: 512B [avg rate: 20MB/s]
wlroots0.16-devel-0.16.2_1.x86_64.xbps: [63KB 6%] 140MB/s ETA: 00m00s
wlroots0.16-devel-0.16.2_1.x86_64.xbps: 63KB [avg rate: 2187MB/s]
wlroots0.16-devel-0.16.2_1: verifying RSA signature...
wlroots-devel-0.16.99_1.x86_64.xbps.sig2: [512B 100%] 17MB/s ETA: 00m00s
wlroots-devel-0.16.99_1.x86_64.xbps.sig2: 512B [avg rate: 17MB/s]
wlroots-devel-0.16.99_1.x86_64.xbps: [604B 100%] 15MB/s ETA: 00m00s
wlroots-devel-0.16.99_1.x86_64.xbps: 604B [avg rate: 15MB/s]
wlroots-devel-0.16.99_1: verifying RSA signature...

[*] Verifying package integrity
brotli-1.1.0_1: verifying RSA signature...
libpng-1.6.40_1: verifying RSA signature...
freetype-2.13.2_1: verifying RSA signature...
fontconfig-2.14.2_1: verifying RSA signature...
util-linux-common-2.38.1_4: verifying RSA signature...
libblkid-2.38.1_4: verifying RSA signature...
libmount-2.38.1_4: verifying RSA signature...
glib-2.78.0_3: verifying RSA signature...
libXau-1.0.11_1: verifying RSA signature...
libXdmcp-1.1.4_1: verifying RSA signature...
libxcb-1.16_1: verifying RSA signature...
libX11-1.8.7_1: verifying RSA signature...
libXext-1.3.5_1: verifying RSA signature...
libXrender-0.9.11_1: verifying RSA signature...
lzo-2.10_2: verifying RSA signature...
pixman-0.42.2_1: verifying RSA signature...
cairo-1.18.0_1: verifying RSA signature...
expat-devel-2.5.0_1: verifying RSA signature...
brotli-devel-1.1.0_1: verifying RSA signature...
bzip2-devel-1.0.8_2: verifying RSA signature...
zlib-devel-1.3_1: verifying RSA signature...
libpng-devel-1.6.40_1: verifying RSA signature...
freetype-devel-2.13.2_1: verifying RSA signature...
libuuid-2.38.1_4: verifying RSA signature...
libuuid-devel-2.38.1_4: verifying RSA signature...
fontconfig-devel-2.14.2_1: verifying RSA signature...
xorgproto-2023.2_1: verifying RSA signature...
libXau-devel-1.0.11_1: verifying RSA signature...
libXdmcp-devel-1.1.4_1: verifying RSA signature...
libxcb-devel-1.16_1: verifying RSA signature...
xtrans-1.5.0_1: verifying RSA signature...
libX11-devel-1.8.7_1: verifying RSA signature...
libXext-devel-1.3.5_1: verifying RSA signature...
libXrender-devel-0.9.11_1: verifying RSA signature...
dbus-libs-1.14.10_1: verifying RSA signature...
dbus-devel-1.14.10_1: verifying RSA signature...
liblzma-devel-5.4.4_1: verifying RSA signature...
libzstd-devel-1.5.5_2: verifying RSA signature...
elfutils-devel-0.189_1: verifying RSA signature...
libffi-devel-3.3_2: verifying RSA signature...
libblkid-devel-2.38.1_4: verifying RSA signature...
libmount-devel-2.38.1_4: verifying RSA signature...
pcre2-devel-10.42_1: verifying RSA signature...
libglib-devel-2.78.0_3: verifying RSA signature...
lzo-devel-2.10_2: verifying RSA signature...
pixman-devel-0.42.2_1: verifying RSA signature...
cairo-devel-1.18.0_1: verifying RSA signature...
libdisplay-info-0.1.1_1: verifying SHA256 hash...
libdisplay-info-devel-0.1.1_1: verifying RSA signature...
libpciaccess-0.16_1: verifying RSA signature...
libdrm-2.4.115_1: verifying RSA signature...
libliftoff-0.4.1_1: verifying SHA256 hash...
fribidi-1.0.13_1: verifying RSA signature...
fribidi-devel-1.0.13_1: verifying RSA signature...
graphite-1.3.14_1: verifying RSA signature...
graphite-devel-1.3.14_1: verifying RSA signature...
icu-libs-73.2_2: verifying RSA signature...
icu-devel-73.2_2: verifying RSA signature...
libharfbuzz-8.2.2_1: verifying RSA signature...
libxml2-2.11.4_4: verifying RSA signature...
harfbuzz-devel-8.2.2_1: verifying RSA signature...
libXft-2.3.8_1: verifying RSA signature...
libXft-devel-2.3.8_1: verifying RSA signature...
libdatrie-0.2.13_1: verifying RSA signature...
libthai-0.1.29_1: verifying RSA signature...
libdatrie-devel-0.2.13_1: verifying RSA signature...
libthai-devel-0.1.29_1: verifying RSA signature...
pango-1.50.14_1: verifying RSA signature...
pango-xft-1.50.14_1: verifying RSA signature...
pango-devel-1.50.14_1: verifying RSA signature...
Vulkan-Headers-1.3.231.1_1: verifying RSA signature...
eudev-libudev-3.2.12_1: verifying RSA signature...
eudev-libudev-devel-3.2.12_1: verifying RSA signature...
libpciaccess-devel-0.16_1: verifying RSA signature...
libdrm-devel-2.4.115_1: verifying RSA signature...
wayland-1.22.0_1: verifying RSA signature...
libgbm-23.1.3_1: verifying RSA signature...
libgbm-devel-23.1.3_1: verifying RSA signature...
libglvnd-1.6.0_1: verifying RSA signature...
libglvnd-devel-1.6.0_1: verifying RSA signature...
libevdev-1.13.0_1: verifying RSA signature...
libgudev-237_1: verifying RSA signature...
libwacom-2.8.0_1: verifying RSA signature...
mtdev-1.1.6_1: verifying RSA signERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/cta.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/cvt.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/displayid.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/dmt.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/edid.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/gtf.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/include/libdisplay-info/info.h' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/lib/pkgconfig/libdisplay-info.pc' already installed by package libdisplay-info-0.1.1_1.
ERROR: libdisplay-info-devel-0.1.1_1: file `/usr/lib/libdisplay-info.so' already installed by package libdisplay-info-0.1.1_1.
Transaction failed! see above for errors.
ature...
libinput-1.23.0_1: verifying RSA signature...
libinput-devel-1.23.0_1: verifying RSA signature...
libelogind-246.10_3: verifying RSA signature...
elogind-devel-246.10_3: verifying RSA signature...
libseat-0.8.0_1: verifying RSA signature...
libseat-devel-0.8.0_1: verifying RSA signature...
libxkbfile-1.1.2_1: verifying RSA signature...
xkbcomp-1.4.6_1: verifying RSA signature...
xkeyboard-config-2.40_1: verifying RSA signature...
libxkbcommon-1.5.0_1: verifying RSA signature...
libxkbcommon-x11-1.5.0_1: verifying RSA signature...
libxkbregistry-1.5.0_1: verifying RSA signature...
libxkbcommon-devel-1.5.0_1: verifying RSA signature...
vulkan-loader-1.3.231.2_1: verifying RSA signature...
wayland-devel-1.22.0_1: verifying RSA signature...
wayland-protocols-1.32_1: verifying RSA signature...
xcb-util-errors-1.0.1_1: verifying RSA signature...
xcb-util-renderutil-0.3.10_1: verifying RSA signature...
xcb-util-wm-0.4.2_1: verifying RSA signature...
xcb-proto-1.16.0_2: verifying RSA signature...
xcb-util-errors-devel-1.0.1_1: verifying RSA signature...
xcb-util-renderutil-devel-0.3.10_1: verifying RSA signature...
xcb-util-0.4.1_1: verifying RSA signature...
xcb-util-devel-0.4.1_1: verifying RSA signature...
xcb-util-wm-devel-0.4.2_1: verifying RSA signature...
libfontenc-1.1.7_1: verifying RSA signature...
libXfont2-2.0.6_1: verifying RSA signature...
libepoxy-1.5.10_1: verifying RSA signature...
e2fsprogs-libs-1.47.0_1: verifying RSA signature...
libsasl-2.1.28_2: verifying RSA signature...
libldap-2.6.6_1: verifying RSA signature...
mit-krb5-libs-1.21.2_3: verifying RSA signature...
libtirpc-1.3.2_1: verifying RSA signature...
libxcvt-0.1.2_1: verifying RSA signature...
libxshmfence-1.3_2: verifying RSA signature...
nettle-3.9.1_1: verifying RSA signature...
xorg-server-common-21.1.9_1: verifying RSA signature...
xorg-server-xwayland-23.2.1_1: verifying RSA signature...

[*] Collecting package files
brotli-1.1.0_1: collecting files...
libpng-1.6.40_1: collecting files...
freetype-2.13.2_1: collecting files...
fontconfig-2.14.2_1: collecting files...
util-linux-common-2.38.1_4: collecting files...
libblkid-2.38.1_4: collecting files...
libmount-2.38.1_4: collecting files...
glib-2.78.0_3: collecting files...
libXau-1.0.11_1: collecting files...
libXdmcp-1.1.4_1: collecting files...
libxcb-1.16_1: collecting files...
libX11-1.8.7_1: collecting files...
libXext-1.3.5_1: collecting files...
libXrender-0.9.11_1: collecting files...
lzo-2.10_2: collecting files...
pixman-0.42.2_1: collecting files...
cairo-1.18.0_1: collecting files...
expat-devel-2.5.0_1: collecting files...
brotli-devel-1.1.0_1: collecting files...
bzip2-devel-1.0.8_2: collecting files...
zlib-devel-1.3_1: collecting files...
libpng-devel-1.6.40_1: collecting files...
freetype-devel-2.13.2_1: collecting files...
libuuid-2.38.1_4: collecting files...
libuuid-devel-2.38.1_4: collecting files...
fontconfig-devel-2.14.2_1: collecting files...
xorgproto-2023.2_1: collecting files...
libXau-devel-1.0.11_1: collecting files...
libXdmcp-devel-1.1.4_1: collecting files...
libxcb-devel-1.16_1: collecting files...
xtrans-1.5.0_1: collecting files...
libX11-devel-1.8.7_1: collecting files...
libXext-devel-1.3.5_1: collecting files...
libXrender-devel-0.9.11_1: collecting files...
dbus-libs-1.14.10_1: collecting files...
dbus-devel-1.14.10_1: collecting files...
liblzma-devel-5.4.4_1: collecting files...
libzstd-devel-1.5.5_2: collecting files...
elfutils-devel-0.189_1: collecting files...
libffi-devel-3.3_2: collecting files...
libblkid-devel-2.38.1_4: collecting files...
libmount-devel-2.38.1_4: collecting files...
pcre2-devel-10.42_1: collecting files...
libglib-devel-2.78.0_3: collecting files...
lzo-devel-2.10_2: collecting files...
pixman-devel-0.42.2_1: collecting files...
cairo-devel-1.18.0_1: collecting files...
libdisplay-info-0.1.1_1: collecting files...
libdisplay-info-devel-0.1.1_1: collecting files...
=> ERROR: Please see above for the real error, exiting...

</details> 

I wonder if it has to do with the fact that libdisplay-info is in the official repos now? I should see if re-cloning the repos would help.

**Comment by Makrennel** [comment]
> I should probably mention that I was trying to build v0.31.0 😅
> 
> According to the [Hyprland wiki](https://wiki.hyprland.org/Getting-Started/Installation/), it is now using C++ 23:
> 
> > Hyprland uses the C++23 standard, so both your compiler and your C++ library has to support that (`gcc>=13.0.0` or `clang>=15`). On Clang-based systems libc++ may be used by default, so until libc++ supports C++23 you have to pass `-stdlib=libstdc++` or switch to GCC.
> 
> So according to that it should be possible. When I was attempting to build it said to use c++2b for C++ 23.

Yep, it should be possible, it's just a little annoying to make xbps-src use Clang - at least doing it the technically "correct" way of modifying `common/xbps-src/shutils/common.sh` - but I suppose you can just modify the variables in `do_build` just before compiling Hyprland.

Anyways, this is a conversation for issue #12 

> 
> `./xbps-src pkg hyprland` after following instructions in README
> I wonder if it has to do with the fact that libdisplay-info is in the official repos now? I should see if re-cloning the repos would help.

Yes, they split `libdisplay-info` with a separate `-devel` subpackage which is what's causing problems. The same will likely happen if `libliftoff` gets added.
