### ISSUE TITLE
Building Hyprland 0.30.0+

### ISSUE THREAD

**Issue by RedNekoderr** [Makrennel/hyprland-void#12]
I was able to install hyprland 0.30... But for this I had to compile gcc13 using xbps-src... I am currently the only one who can use the new versions, although I can share .xbps files for gcc13 and dependencies. 

I think we should reach out to the void developers. Their compilation error is literally that one server with a dependency died and they did not change it in the gcc template

**Comment by zen0bit** [comment]
PR with new version
and all needed templates?

**Comment by RedNekoderr** [comment]
> PR with new version and all needed templates?

My gcc template: [https://github.com/RedNekoderr/gcc-template](url)
In template hyprland, I just changed the version and the checksum

**Comment by RedNekoderr** [comment]
By the way, clang 15, which is in repositories, is also suitable for building hyprland 0.30. Can anyone try to compile it like this?

**Comment by Makrennel** [comment]
> I think we should reach out to the void developers. Their compilation error is literally that one server with a dependency died and they did not change it in the gcc template

Hey, absolutely do reach out to them. I figured it would probably be pretty simple to get a functional gcc13 template, but just for risk of causing unforeseen problems with other programs I'm not interested in carrying a gcc template replacement in this repository.

**Comment by rehanzo** [comment]
There's already a pr for an updated gcc, just hasn't been merged yet

**Comment by altosys** [comment]
gcc 13.2.0 has been rolled out on void, can we get these long awaited Hyprland updates now?

**Comment by Makrennel** [comment]
Updated to 0.34.0, but I don't currently have a machine set up that can test the package once installed, let me know if there's issues with the package.

**Comment by dom0** [comment]
I tried to build new version and it seems there is some problem with the wlroots version:
Hyprland: symbol lookup error: /usr/lib/libwlroots.so.13032: undefined symbol: drmModeCloseFB

anyway thanks for your work

**Comment by Makrennel** [comment]
> I tried to build new version and it seems there is some problem with the wlroots version: Hyprland: symbol lookup error: /usr/lib/libwlroots.so.13032: undefined symbol: drmModeCloseFB

Should be fixed with #19
