### ISSUE TITLE
Build error: cannot guess required shlibs

### ISSUE THREAD

**Issue by Poly2it** [Makrennel/hyprland-void#13]
On a quite fresh void install, `./xbps-src pkg hyprland` fails in `running pre-pkg hook: 04-generate-runtime-deps` with
```
=> ERROR: hyprland-0.29.1_2: cannot guess required shlibs, aborting!
```

I am also getting two other errors before the fatal one in the same build step:
```
    SONAME: libdisplay-info.so.1 <-> UNKNOWN PKG PLEASE FIX!
    SONAME: libliftoff.so.0 <-> UNKNOWN PKG PLEASE FIX!
```

**Comment by Poly2it** [comment]
I might have gotten it to build.

**Comment by Makrennel** [comment]
@Poly2it You missed Step 4 in [usage](https://github.com/Makrennel/hyprland-void#usage)
