### ISSUE TITLE
libwlroots error when building hyprland 0.34.0

### ISSUE THREAD

**Issue by altosys** [Makrennel/hyprland-void#20]
After building hyprland off master to compile 0.34.0 I get this error from libwlroots when launching:
```
Hyprland: symbol lookup error: /usr/lib64/libwlroots.so.13032: undefined symbol: drmModeCloseFB
```
The build process for the package finishes successfully without terminating, but the output does state this:
```
hyprland-0.34.0_1: libwlroots.so.13032 not found in common/shlibs.
```

**Comment by Makrennel** [comment]
This is due to void's libdrm being out of date, and I forgot to add the updated libdrm version to the hyprland dependencies requirements so it would usually just void's libdrm. Should be fixed in #19 and maybe also if you run `./xbps-src update-sys`
