### ISSUE TITLE
what happened to hyprland-nvidia?

### ISSUE THREAD

**Issue by zmeyka3310** [Makrennel/hyprland-void#23]
hybrind gpu setup, apps running on the nvidia gpu freeze from time to time, only fix being changing workspaces. may be related to vrr and direct scanout, tho im not sure

**Comment by Makrennel** [comment]
The `hyprland-nvidia` package is just a dummy package now; it has the normal `hyprland` package listed as a dependency instead. Unofficial nvidia patches were made redundant in [v0.33.0](https://github.com/hyprwm/Hyprland/releases/tag/v0.33.0)

**Comment by zmeyka3310** [comment]
for the people that find this thread later, the issue is steamtinkerlaunch
