### ISSUE TITLE
hyprlock, hypridle, hyprlang 0.4.0

### ISSUE THREAD

**Issue by DonPiotr** [Makrennel/hyprland-void#32]
Hi,

I was trying to make my own templates for hyprlock, hypridle and update hyprlang  to 0.4.0.
After rebuild hyprlang, when I tried to build other packages I got those messages:

SONAME: libhyprlang.so.1 <-> UNKNOWN PKG PLEASE FIX!
...
=> ERROR: hyprlock-0.1.0_1: cannot guess required shlibs, aborting!

In shlibs I have:
libhyprlang.so hyprlang-0.4.0_1

I know, it is not issue with this repo, but with my ignorance,
but anybody have some clue?

Thx.

**Comment by Makrennel** [comment]
> In shlibs I have:
> libhyprlang.so hyprlang-0.4.0_1

Probably needs to be
`libhyprlang.so.1 hyprlang-0.4.0_1`

**Comment by DonPiotr** [comment]
Thx.
I added this line and it's working.
