### ISSUE TITLE
Can't start hyprland

### ISSUE THREAD

**Issue by Baturax** [Makrennel/hyprland-void#40]
I installed and everything worked fine. but when i try to start Hyprland it gives error. I also isntalled and started elogind.
`[CRITICAL] Critical error thrown: XDG_RUNTIME_DIR is not set!
terminate called after throwing an instance of 'std::runtime_error'
  what():  XDG_RUNTIME_DIR is not set!
fish: Job 1, 'Hyprland' terminated by signal SIGABRT (Abort)
`

**Comment by Baturax** [comment]
btw i set xdg using this: echo "export XDG_RUNTIME_DIR=/run/user/$(id -u)" >> ~/.bashrc but now got another error.
[hyprlandCrashReport13603.txt](https://github.com/Makrennel/hyprland-void/files/14575638/hyprlandCrashReport13603.txt)

**Comment by Baturax** [comment]
okay sorry for this. it was my bad. i set it to /tmp and worked now.

**Comment by Makrennel** [comment]
Yeah, elogind or systemd is usually used to automatically set this environment variable, otherwise you have to set it yourself if you're only using seatd by itself.
