### ISSUE TITLE
Include in abyss-packages

### ISSUE THREAD

**Issue by zen0bit** [Makrennel/hyprland-void#44]
[abyss-packages](https://github.com/mobinmob/abyss-packages)

Can do it my self, but since you are maintainer, you wanna do it yourself?

PS: maybe some github action, which will trigger PR to abyss repo, if new release of template comes out?

**Comment by Makrennel** [comment]
Why?

**Comment by zen0bit** [comment]
Why not?

**Comment by Makrennel** [comment]
> Why not?

That repo doesn't have a format which supports shlibs, and I don't care to have to manage my repository based on what works for another repository. What would even be the purpose of putting this on there?
