### ISSUE TITLE
Legacy Renderer

### ISSUE THREAD

**Issue by ktnlikeasmallcat** [Makrennel/hyprland-void#46]
Thanks for all this. Ive been trying to get everything working on a new install on some older hardware, and I've run up against the need to test [hyprland's legacy renderer](https://wiki.hyprland.org/Getting-Started/Installation/#custom-installation-legacy-renderer-etc) but im not quite sure how to approach the problem in void's src pkg context, can I ask for some guidance? I've got hyprland loading just fine (i think) using tuigreet as of now, but nothing will show up on screen, and i cant imagine what else I could tweak at this point.

**Comment by Makrennel** [comment]
I think you just have to add `-DLEGACY_RENDERER:BOOL=true` to the cmake flags

**Comment by ktnlikeasmallcat** [comment]
I put that flag in both the 'musl' and 'else' area rebuilt and reinstalled, but it didn't solve the issue keeping me from opening anything in the hyprland session, whether launched through dbus-run-session via tuigreet or from tty and running either elogind or seatd + pam_rundir. 

Thank you, though.
