### ISSUE TITLE
libhyprlang.so shlib broken

### ISSUE THREAD

**Issue by ANA280044** [Makrennel/hyprland-void#48]
tried to update, got this output
`=> xbps-src: updating your system, confirm to proceed...
hyprpaper-0.6.0_1: broken, unresolvable shlib libhyprlang.so
xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib libhyprlang.so
Transaction aborted due to unresolved shlibs.`

**Comment by zmeyka3310** [comment]
remove hyprland with what is depending on (and whatever it will complain about when updating) it and install it back after everything is removed and you ran the update
