### ISSUE TITLE
Hyprland 0.39.0 is out

### ISSUE THREAD

**Issue by zen0bit** [Makrennel/hyprland-void#51]
# Main change:
## switched to: `hyprland-wlroots`
read more in release page...
[releases](https://github.com/hyprwm/Hyprland/releases/)

Not working on updating yet

**Comment by soanvig** [comment]
Before we solve one version build, the next version comes out :D

**Comment by Makrennel** [comment]
I can't test running it because I've switched my system over to NixOS, but I've [updated the template to 0.39.1](https://github.com/Makrennel/hyprland-void/commit/40a909b0d87508276e6d5790362e505c4fe4e793) and compilation seems to work alright on both glibc and musl distrobox images, although cross-compilation fails due to sanity test and I can't be bothered to fix that. I'll try to keep updating this either way, but I won't be testing much beyond making sure it actually builds.

**Comment by tommyalatalo** [comment]
I'm unable to build using the latest commit 04f558a. The build process tries to fetch `xz`, specifically version 5.6.0 which was one of the compromised versions in the recent incident, the tarball for that version has been taken down from github.

I tried grepping for `xz` in the hyprland-void repo, but there's no mention of it, so I guess the xz dependency is a nested one for something else?
```
=> xz-5.6.0_1: building with [gnu-configure] (dependency of zstd) for x86_64...
   [runtime] liblzma-5.6.0_1: not found (subpkg, ignored)
   [runtime] liblzma-5.6.0_1: not found (subpkg, ignored)
=> xz-5.6.0_1: running do-fetch hook: 00-distfiles ...
=> xz-5.6.0_1: fetching distfile 'xz-5.6.0.tar.gz' from 'https://github.com/tukaani-project/xz/releases/download/v5.6.0/xz-5.6.0.tar.gz'...
https://github.com/tukaani-project/xz/releases/download/v5.6.0/xz-5.6.0.tar.gz: Not Found
=> ERROR: xz-5.6.0_1: failed to fetch 'xz-5.6.0.tar.gz'.
```

**Comment by Makrennel** [comment]
> The build process tries to fetch `xz`, specifically version 5.6.0 which was one of the compromised versions in the recent incident, the tarball for that version has been taken down from github.

@tommyalatalo Have you updated your clone of `void-packages` or tried starting from a fresh one? It sounds like your system has the reverted version installed, so void-packages is trying to download the more "up to date" version based on the template that's in its repository but the file it's referencing has been removed by github.

**Comment by tommyalatalo** [comment]
> > The build process tries to fetch `xz`, specifically version 5.6.0 which was one of the compromised versions in the recent incident, the tarball for that version has been taken down from github.
> 
> @tommyalatalo Have you updated your clone of `void-packages` or tried starting from a fresh one? It sounds like your system has the reverted version installed, so void-packages is trying to download and build the more "up to date" version based on the template that's in its repository but the file it's referencing has been removed by github.

_facefalm_ I forgot to pull void-packages, so that was causing the `xz` problem above, but now that both my `hyprland-void` and `void-packages` repos are up to date a new error popped up when trying to update. Building hyprland works now, but running `xbps-src update-sys` errors out with this:

```
=> xbps-src: updating your system, confirm to proceed...
xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so'
Transaction aborted due to unresolved shlibs.
```

**Comment by Makrennel** [comment]
> ```
> => xbps-src: updating your system, confirm to proceed...
> xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so'
> Transaction aborted due to unresolved shlibs.
> ```

You have to re-append `common/shlibs`, it changes every now and then

**Comment by tommyalatalo** [comment]
> > ```
> > => xbps-src: updating your system, confirm to proceed...
> > xdg-desktop-portal-hyprland-1.3.1_1: broken, unresolvable shlib `libhyprlang.so'
> > Transaction aborted due to unresolved shlibs.
> > ```
> 
> You have to re-append `common/shlibs`, it changes every now and then

So I did do that, actually cleared out the entire void-packages repo, appended shlibs and copied the hyprland templates, but `update-sys` still fails with the libhyprlang.so error.

**Comment by Makrennel** [comment]
Try removing it and building hyprlang and xdph again

**Comment by tommyalatalo** [comment]
If I remove libhyprlang from shlibs I get a build error like below. Not sure if that's what you meant by removing it.
```
   SONAME: libhyprlang.so.2 <-> UNKNOWN PKG PLEASE FIX!
   SONAME: libhyprcursor.so.0 <-> hyprcursor>=0.1.5_1
   SONAME: libGLESv2.so.2 <-> libGLES>=1.0_1
   SONAME: libstdc++.so.6 <-> libstdc++>=4.4.0_1
   SONAME: libm.so.6 <-> glibc>=2.39_1
   SONAME: libgcc_s.so.1 <-> libgcc>=4.4.0_1
   SONAME: libc.so.6 <-> glibc>=2.39_1
   SONAME: libtomlplusplus.so.3 <-> tomlplusplus>=3.4.0_1
=> ERROR: hyprland-0.39.1_1: cannot guess required shlibs, aborting!
```

**Comment by tommyalatalo** [comment]
Finally got around to this again, just wanted to leave a reference here that yeah, it worked to uninstall the erroring packages and then build and install everything after that.
