### ISSUE TITLE
Make Hyprland-Git 🥺

### ISSUE THREAD

**Issue by blacklightpy** [Makrennel/hyprland-void#53]
I had built Hyprland 0.38.1 a day after it came out (was a messy process so I couldn't make a PR). But it was useless as hyprexpo needs hyprland-git.

I'll try to help, but I'm a bit busy, and I've never built against used git in an XBPS template.. so I don't know what to expect.

**Comment by Makrennel** [comment]
While git packages are possible, they fundamentally do not fit within the format of xbps. The best approach is to build against a particular desired commit. If you want something akin to Arch's git packages where you're just building from the latest git commit you'll have to consciously rebuild and force reinstall every time there's a commit - xbps will not facilitate git packages for you.

Really with Hyprland you're better off just building from source and installing in `/usr/local` as you traditionally would if you want plugins or git, it'll save you a huge deal of headache. Pretty much every distro I've tried has had problems with plugins relating to Hyprland built from tagged releases and packaged natively.

If you must, you could copy the `hostmakedepends` and `makedepends` from the Hyprland template into a meta package template and use that a starting point to build the git version with the necessary dependencies for `hyprpm` to work. I'm not interested in keeping a shabby half-broken git package for Hyprland with constantly moving targets in this repository, but I might consider adding a meta package for dependencies so people can easily get started with the make file without having to manually install a bajillion different dependencies.

**Comment by Makrennel** [comment]
I actually came back round to this, there are now nightly packages available in the binary repository built from git.
