### ISSUE TITLE
failed to install target dependencies! (error 8)

### ISSUE THREAD

**Issue by KuroSeongbae** [Makrennel/hyprland-void#6]
Heya, I'm getting following error when trying to `./xbps-src pkg hyprland`:

```
=> ERROR: hyprland-0.27.2_1: failed to install target dependencies! (error 8)
libxml2-2.11.2_2: broken, unresolvable shlib `libicuuc.so.72'
```
void-src repo and hyperland-void repo are both up to date and I follwed the instructions in the README.
I also can't find a decent solution in the web for this issue.

**Comment by Makrennel** [comment]
Hey, have you got any more information regarding how you set up your cloned void-packages repository before you followed the instructions in the README?

**Comment by KuroSeongbae** [comment]
I actually just used the quick start guide and never installed something with it. I also did a hard reset already.

But after deleting the void-pacakges repo and setting it up again I could install hyprland.
