### ISSUE TITLE
Modules don't work  "hyprland/workspaces", "hyprland/window"

### ISSUE THREAD

**Issue by sofijacom** [Makrennel/hyprland-void#61]
Hyprland v0.40.0 . No display of desktops and icons in wybar

**Comment by Makrennel** [comment]
I don't really know what you're saying here.

**Comment by sofijacom** [comment]
> Я действительно не понимаю, о чем вы здесь говорите.


![2024-05-16_17-35](https://github.com/Makrennel/hyprland-void/assets/107557749/afb91188-c127-4d7f-9162-83cba0136665)

**Comment by Makrennel** [comment]
This isn't related to the packaging of Hyprland in this template.

I think some backend stuff was changed relating to workspaces in 0.40.0 and you'll have to wait for Waybar to update to fix it.

**Comment by sofijacom** [comment]
Let's hope this is exactly the case

**Comment by sofijacom** [comment]
Wait a long time, compile faster. Thanks for the tip, now everything works
![screenshot-20240516-182128](https://github.com/Makrennel/hyprland-void/assets/107557749/0d995293-621d-4ce3-864c-3a70a7fd85c5)
