### ISSUE TITLE
Xdg runtime error 

### ISSUE THREAD

**Issue by zed1214** [Makrennel/hyprland-void#63]
After trying to install the hyprland, my logs, after running Hyprland by command Hyprland, look like:
hyprland std::runtime_error what():wlr_backend_autocreate() failed.
Please help to resolve the errors or make new correct release

**Comment by Makrennel** [comment]
Need more information. This is one of those errors that really means nothing with how many times I've got it for different problems / seen in Hyprland issues.

**Comment by zed1214** [comment]
> Need more information like setup/drivers and so on. This is one of those errors that really means nothing with how many times I've got it for different problems / seen in Hyprland issues.
> 
> 
> `debug:disable_logs` may need to be set false and `debug:enable_stdout_logs` true see: https://wiki.hyprland.org/Configuring/Variables/#debug

Thanks, but now, with the error of wlr_backend_autocreate, I have:
[CRITICAL] m_sWLRLbackend was NULL! This usually means wlroots could not find a GPU or encountered some issues.
But I've installed the Nvidia proprietary driver and already configured the grub.cfg

**Comment by soanvig** [comment]
If you are using Nvidia driver please make sure to apply changes: https://wiki.hyprland.org/Nvidia/
I've been there. When it was hyprland 0.36 it just refused to run, with some random WLR backend error as well.
One of the newer versions randomly fixed that.

**Comment by zed1214** [comment]
> If you are using Nvidia proprietary driver please make sure to apply changes: https://wiki.hyprland.org/Nvidia/. Also check that your DRM whatever is enabled, there is a way to do it (Google).
> I've been there. When it was hyprland 0.36 it just refused to run, with some random WLR backend error as well.
> One of the newer versions randomly fixed that.
Yes, I applied all of the changes to GRUB, but Void Linux does not consist of mkinitcpio to configure all parameters

**Comment by Makrennel** [comment]
@zed1214 shot in the dark here, but this has stopped mine working before, have you added your user to the `_seatd` group? If you see any "libseat ... Permission denied" errors it might be this.

**Comment by zed1214** [comment]
> @zed1214 shot in the dark here, but this has stopped mine working before, have you added your user to the `_seatd` group? If you see any "libseat ... Permission denied" errors it might be this.

No all of my errors I'm already described
