### ISSUE TITLE
black screen while screensharing / recording on obs after upadating xdg-desktop-portal-hyprland

### ISSUE THREAD

**Issue by Anik200** [Makrennel/hyprland-void#67]
![image](https://github.com/Makrennel/hyprland-void/assets/87752958/8b1750fa-b3ef-450f-acfa-c24c3fe9067e)
the preview is black even though i selected the screen
![image](https://github.com/Makrennel/hyprland-void/assets/87752958/9a5a9343-eed3-430d-b391-32f16d5daf8d)

**Comment by soanvig** [comment]
Did you try "allow restore token"?

**Comment by Anik200** [comment]
Yes, I did. Even though same results. However removing the old hyprland
installation which i did manually and reinstalling the ones from the
voidconfig.d fixed the issue.

**Comment by soanvig** [comment]
BTW make sure you have `xdg-desktop-portal-hyprland` installed. Maybe previously you didn't have and now you do

**Comment by Anik200** [comment]
Yes, thanks 👍

**Comment by Makrennel** [comment]
Closing as you're saying it's fixed

**Comment by Anik200** [comment]
something weird happened, i rebooted and it dosent work all of a sudden. i did reboot a couple of times and it seems to work a few times but not mostly. i feel like it dosent get started at boot. xdph is installed but wont run everytime on boot

**Comment by Makrennel** [comment]
> i feel like it dosent get started at boot. xdph is installed but wont run everytime on boot

Have you declared it with `exec-once` in your hyprland config file? It's not supposed to start "on boot". Most distros start it with a systemd user service and manages it using the xdg-desktop-portal-config, but of course void linux doesn't have systemd so you need to manually start it.

**Comment by Anik200** [comment]
Which command to start it ?

**Comment by Makrennel** [comment]
> Which command to start it ?

Should be `exec-once=/usr/libexec/xdg-desktop-portal-hyprland` but you might also need `exec-once=/usr/libexec/xdg-desktop-portal`

**Comment by Anik200** [comment]
It dosent work and i still get a black screen while trying to screenshare

**Comment by Anik200** [comment]
Alright so i reinstalled everything and added both of the exec once to my
hyprland.conf and it now works flawlessly, and thanks a lot again for your
precious time.
