### ISSUE TITLE
bump hyprland to 0.42.0

### ISSUE THREAD

**Issue by zmeyka3310** [Makrennel/hyprland-void#71]
what the title says, tho i heard its sometimes unstable

**Comment by Swomp2** [comment]
So, what about hyprland 0.42?

**Comment by zmeyka3310** [comment]
> So, what about hyprland 0.42?

makrennel hasnt been online for 10 days, sometimes we had to wait upwards of 2 weeks to get a version bump, so except to wait a bit more

**Comment by Makrennel** [comment]
Done.

Nightly is gone now. Was a shit idea to begin with, and requires GCC 14 now which void doesn't have.

**Comment by Swomp2** [comment]
Oh, thank you very much:)
