### ISSUE TITLE
Hyprcursor dependency issue?

### ISSUE THREAD

**Issue by lcassa** [Makrennel/hyprland-void#75]
Hi, I've just created a fresh void-package and hyprland-void folders, run the regular steps, but when I try running Hyprland command I get an error message saying Hyprland undefined symbol `_ZN10Hyprcursor18CHyprcursorManagerC1EPKcNS_15SManagerOptionsE`

**Comment by lcassa** [comment]
I've used a previous version to get hyprland back working, but I'd really like to use the latest version

**Comment by Makrennel** [comment]
Have you had this problem with the binary package?

**Comment by lcassa** [comment]
No, manually installing. Using the readme steps, what I usually do.

Em sex., 23 de ago. de 2024, 19:27, Makrennel ***@***.***>
escreveu:

**Comment by Makrennel** [comment]
I can only suggest uninstalling everything and rebuilding again from scratch, or trying the binaries in the repository. From what I've seen looking through Hyprland issues this appears to be an error relating to a build mismatch, and without anyone else saying they have this issue this I cannot confirm that anything is wrong with the templates themselves.

**Comment by lcassa** [comment]
My processor is ARM, so I can't use the repository. I already did it from
scratch, but I'll do it again and report back.

Em sáb., 24 de ago. de 2024, 13:52, Makrennel ***@***.***>
escreveu:

**Comment by lcassa** [comment]
@Makrennel I just did it from scratch, exactly the same error... guess I'll have to stay behind until next release

**Comment by Makrennel** [comment]
There might be something ARM specific about Hyprcursor's packaging I'm completely missing, but I don't really have any references to work off, nor means to test it.

> guess I'll have to stay behind until next release

Unfortunately that could be a long way off, even if Hyprland updates soon – git (and any subsequent versions) will require a version of gcc void yet again does not have available.

Have you tried using Nix?

**Comment by lcassa** [comment]
@Makrennel I found the issue and a solution

`diff --git a/common/shlibs b/common/shlibs
index a0dc51b..f687f35 100644
--- a/common/shlibs
+++ b/common/shlibs
@@ -1,6 +1,6 @@
 libsdbus-c++.so.1 sdbus-cpp-1.5.0_1
 libhyprlang.so.2 hyprlang-0.5.0_1
-libhyprcursor.so.0 hyprcursor-0.1.5_1
+libhyprcursor.so.0 hyprcursor-0.1.9_1
 libtomlplusplus.so.3 tomlplusplus-3.4.0_1
 libhyprutils.so.1 hyprutils-0.2.1_1
 libaquamarine.so.2 aquamarine-0.3.0_1`

I don't know why your hyprcursor version was 0.1.5_1, neither if I should use the latest version which is 0.1.9_1, but that change fixed the issue. I'm not going to close the issue as you might want to change something in the repo.

**Comment by Makrennel** [comment]
> I don't know why your hyprcursor version was 0.1.5_1, neither if I should use the latest version which is 0.1.9_1, but that change fixed the issue. I'm not going to close the issue as you might want to change something in the repo.

The version usually doesn't have to be bumped every time the package is updated – the `so` still matches and the version number is a minimum version.

If that fixes it though I'll try changing it, but again I haven't heard this issue crop up for anyone else so far.
