### ISSUE TITLE
v0.43.0

### ISSUE THREAD

**Issue by Anik200** [Makrennel/hyprland-void#77]

**Comment by Makrennel** [comment]
Not possible. New Hyprland version requires a GCC version which hasn't landed in Void Linux repos.

**Comment by dom0** [comment]
@Makrennel 
Hi, if you are interested i patched your last release to build all packages using clang18. I've been using v0.43.0 for a couple of days without encountering any issues.
These changes however break the automatic plugin build via hyprpm (it is however possible to compile them manually with some tricks) and I have no way to test cross-compilation.
As far as you know, are there drakbacks to using clang?

**Comment by zen0bit** [comment]
PR with gcc 14.1.0 in void repos
https://github.com/void-linux/void-packages/pull/50825

PS: Hyprland 0.44.0 already out...

**Comment by Makrennel** [comment]
#80
0.44.0 is now in thanks to @dom0
