### ISSUE TITLE
Help reproduce signing please

### ISSUE THREAD

**Issue by zen0bit** [Makrennel/hyprland-void#81]
Not issue with your repo
(Keep up good work 👍)

I am trying to also build packages in action, but i have problem with signing packages.

Looks like to me that i don't get private.pem

- created new private.pem with passphrase
- created private repo hyprland-void-private-pem with /content/private.pem
- created branches for glib and musl
- created secret in repo with PEM_PAT (new github token) and PRIVAT_PEM_PASSPHRASE (passphrase for privat.pem)

I get xbps-rindex: failed to read the RSA privkey

problem with PEM_PAT i think...

What i missed?

Thanks in advance

**Comment by zen0bit** [comment]
Here is my last action debug
https://github.com/oSoWoSo/hyprland-void/actions/runs/11256284056/job/31298648257#step:10:50

**Comment by zen0bit** [comment]
private repo hyprland-void-private-pem with private.pem

**Comment by Makrennel** [comment]
Yeah, it uses a private repository where the private signing key is stored.
